(* expressions *)
expression = identifier | expression, binary-operator, expression | literal | open-precedent, expression, closed-precedent | expression, condition-operator, expression ;

(* statements *)
statement = (if | while), expression, open-statement-list, statement-list, closed-statement-list |  type, identifier | identifier, assignment, expression ;
statement-list = [statement, [statement-list]] ;

(* literal *)
literal = integer-literal | boolean-literal ;
integer-literal = [subtraction-operator], number ;