(* statements *)
statement-list = [statement, [statement-list]] ;
statement = ("if" | "while"), expression, "{", statement-list, "}" |  type, identifier | identifier, "=", expression ;

(* expressions *)
expression = identifier | expression ("+" | "<") expression | integer | "(", expression, ")" ;